---
sidebar: sidebar 
permalink: learn-about-install.html 
keywords: aws installation, prerequisites, control plane, worker vm, ec2 
summary: 了解如何安裝 NetApp Data Migrator 控制平面和工作虛擬機器。 
---
= 了解如何安裝 NetApp Data Migrator
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Migrator 由一個控制平面和一個或多個工作進程組成，它們協同工作，使用 NFS 和 SMB 傳輸協定執行資料遷移作業。

* *控制平面*：控制平面充當中央管理和控制層。您需要將控制平面部署在 Linux 虛擬機器（VM）上，然後再部署工作進程。
* *Workers*：Workers 是執行實際資料遷移的虛擬機器。您可以根據規模和需求部署多個 Workers。Worker 類型取決於傳輸協定：
+
** Linux 工作者支援 NFS 移轉。
** Windows 工作進程支援 SMB 移轉。




首先，您可以使用 AWS、Azure 或 Google Cloud 服務，或使用 Open Virtual Appliance (OVA) 模板，部署控制平面虛擬機器 (VM) 和 Linux 工作虛擬機器。您可以從 NetApp 支援網站下載部署所需的 NetApp Data Migrator 映像。

部署完成後，建立控制平面 VM 和工作 VM 以存取 NetApp Data Migrator。使用已部署的映像來建立控制平面 VM 和 Linux 工作 VM。使用從 NetApp 支援網站下載的 Windows Worker Installer 建立 Windows 工作 VM。之後，您可以選擇驗證控制平面 VM 或繼續存取 NetApp Data Migrator UI 並連接到控制平面和工作節點。

.接下來呢？
了解如何安裝 NetApp Data Migrator 後，如果您是新客戶，可以在 NetApp 支援網站上link:register-for-account.html["註冊帳戶"]；如果您已有帳戶，則可以繼續link:deploy-control-plane-and-linux-workers.html["部署控制平面和 Linux 工作虛擬機器"]。
